accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('platforms/', include('platforms.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platforms/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'platforms'
urlpatterns = [
    # main 화면
    path('index/', views.index, name="index"),
    
    # 은행 (전체계좌-상세계좌, 이체, 지점찾기)
    path('total_accounts/', views.total_accounts, name="total_accounts"),   # 전체계좌
    path('<str:pk>/accounts/', views.accounts, name="accounts"),                     # 상세계좌
    path('<str:pk>/transfer/', views.transfer, name="transfer"),            # 이체
    path('find_kb/', views.find_kb, name="find_kb"),                        # 지점찾기

    # 증권 (주식계좌, 주식잔고, 주식차트, 종가 UP&DOWN-출석체크,결과보기)
    path('stock_account/', views.stock_account, name="stock_account"),      # 주식 전체계좌
    path('stock/', views.stock, name="stock"),                              # 주식 잔고
    path('stock_charts/', views.stock_charts, name="stock_charts"),         # 주식 차트
    path('stock_game/', views.stock_game, name="stock_game"),               # 종가UP&DOWN
    path('attendance/', views.attendance, name="attendance"),               # 출석체크
    path('updown_result/', views.updown_result, name="updown_result"),      # 결과

    # 카드 (카드목록, 카드추천)
    path('cards/', views.cards, name="cards"),                              # 카드목록
    path('cards_recom/', views.cards_recom, name="cards_recom"),            # 카드추천

    # 습관 (소비습관, 자산현황, myGold 확인하기)
    path('charts/', views.charts, name="charts"),                           # 소비습관
    path('myAsset/', views.myAsset, name="myAsset"),                        # 자산현황
    path('myGold/', views.myGold, name="myGold"),                           # my Gold
    path('setResult/', views.setResult, name="setResult")                   # 예측 값 받아서 정리

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
# User DB
class User(AbstractUser):
    # 이달의 출석 횟수
    check_cnt = models.PositiveIntegerField(default=0, blank=True, null=False)
    # 이달의 성공 횟수
    success = models.PositiveIntegerField(default=0, blank=True, null=False)
    # 오늘 게임을 했나 안했나의 여부 check
    tmp = models.IntegerField(default=-1, blank=True, null=False)
    # 내가 한 찍은 결과 값
    my_result = models.IntegerField(default=0, blank=True, null=False)

platforms/models.py
from django.db import models

# Create your models here.
# 계좌 DB
class Account(models.Model):
    acc_choices = [
        (0, '은행'),
        (1, '증권'),
        (2, '금'),
    ]

    acc_detail = [
        (0, '입출금자유'),
        (1, '예금/적금/주택청약'),
        (2, '골드'),
        (3, '증권'),
    ]

    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name="account")
    acc_num = models.CharField(max_length=30, primary_key=True)  # 계좌번호 PK
    acc_pwd = models.PositiveIntegerField()           # 계좌 비밀번호 (6자리)
    acc_type = models.PositiveIntegerField(choices=acc_choices)     # 계좌 타입 (은행, 증권, 금)
    acc_name = models.CharField(max_length=20)        # 계좌명
    total = models.DecimalField(null=True, blank=True, max_digits=11, decimal_places=4)       # 총 잔액
    created_at = models.DateField()  # 계좌 개설일자
    updated_at = models.DateField(auto_now=True)      # 최근 거래일자
    acc_detail = models.PositiveIntegerField(choices=acc_detail)   # 계좌 디테일
    
    def __str__(self):
        return self.acc_name

# 거래 내역 DB
class Trans(models.Model):
    trans_choices = [
        (0, '식비'),
        (1, '이동통신'),
        (2, '쇼핑'),
        (3, '문화생활'),
        (4, '의료'),
        (5, '교통비'),
    ]
    # trans_id :: PK 자동 생성
    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='trans')
    trans_date = models.DateTimeField()    # 거래 시간
    trans_price = models.DecimalField(max_digits=11, decimal_places=4)          # 거래 금액
    trans_content = models.CharField(max_length=30)                             # 거래 내용 
    trans_type = models.PositiveIntegerField(choices=trans_choices)   


# Card DB
class Card(models.Model):
    # card_id :: 카드 아이디
    card_name = models.CharField(max_length=20)
    card_type = models.BooleanField() # true : 신용카드, false : 체크카드
    card_img = models.ImageField(blank=True, upload_to ="media", null=True)

# Benefit DB
class Benefit(models.Model):
    card = models.ForeignKey(Card, on_delete=models.CASCADE, default='')
    service_name = models.CharField(max_length=20)
    percent = models.IntegerField()
    use_stand = models.TextField()
    month_stand = models.TextField()
    
    class Meta:
        db_table = "kb_platform_benefit"

# lstm model result
class LSTM(models.Model):
    date = models.DateField()
    pred = models.IntegerField() 
    act = models.IntegerField()


# 댓글 DB
# class Comment(models.Model):

accounts/views.py
from django.shortcuts import get_object_or_404, redirect, render
from . models import User
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
#from django.contrib.auth.models import User
from django.db.models import Q

# 1. 로그인
def login(request):
    if request.method == 'POST':
        user_name = request.POST['userID']
        password = request.POST['password']
        user = authenticate(request, username=user_name, password=password)
        if user is not None:
            auth.login(request, user)
            return render(request, 'platforms/index.html')
        else:
            return render(request, 'accounts/login.html', {'error': 'user_name or password is incorrect.'})
    else:
        return render(request, 'accounts/login.html')

# 2. 로그아웃
def logout(request):
    auth.logout(request)
    return render(request, 'platforms/index.html')

# 3. 회원가입    
def register(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            user = User.objects.create_user(
                username=request.POST['userID'],
                password=request.POST['password1'],
                first_name=request.POST['username'],
            )
            auth.login(request, user)
            return redirect('accounts:login')
        return render(request, 'accounts/register.html')
    return render(request, 'accounts/register.html')

platforms/views.py
from django.shortcuts import get_object_or_404, redirect, render
from . models import Card, Benefit, Account, Trans, LSTM
from django.contrib import auth, messages
from django.http import HttpResponseRedirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
from django.db.models import Q
import datetime
from django.db.models import Count, Sum
from django.db.models.functions import TruncMonth, TruncDate, Abs
from django.db.models import Func, F


# Create your views here.
def index(request):
    return render(request, 'platforms/index.html')

# --------------------- 은행 (전체계좌-상세계좌, 이체, 지점찾기) ---------------------
# 1. 전체 계좌 페이지


def total_accounts(request):
    # 해당 user에 해당하는 계좌 list
    all_accounts = Account.objects.filter(user=request.user)
    acc_total = sum(all_accounts.values_list('total', flat=True))

    account_0 = all_accounts.filter(acc_detail=0)
    account_1 = all_accounts.filter(acc_detail=1)
    account_2 = all_accounts.filter(acc_detail=2)

    ###### 입출금 자유 ######
    total_bank0 = []
    for i in range(len(account_0)):
        tmp = 0
        all_trans = Trans.objects.filter(account_id=account_0[i].acc_num)
        tmp_acc = Account.objects.get(acc_num=account_0[i].acc_num)
        for trans in all_trans:
            tmp += trans.trans_price
        total_bank0.append(tmp)
        tmp_acc.total = tmp
        tmp_acc.save()

    ###### 예금 / 적금 / 주택청약 ######
    total_bank1 = []
    for i in range(len(account_1)):
        tmp = 0
        all_trans = Trans.objects.filter(account_id=account_1[i].acc_num)
        tmp_acc = Account.objects.get(acc_num=account_1[i].acc_num)
        for trans in all_trans:
            tmp += trans.trans_price
        total_bank1.append(tmp)
        tmp_acc.total = tmp
        tmp_acc.save()

    ###### 골드 ######
    total_bank2 = []
    for i in range(len(account_2)):
        tmp = 0
        all_trans = Trans.objects.filter(account_id=account_2[i].acc_num)
        tmp_acc = Account.objects.get(acc_num=account_2[i].acc_num)
        for trans in all_trans:
            tmp += trans.trans_price
        total_bank2.append(tmp)
        tmp_acc.total = tmp
        tmp_acc.save()

    context = {
        'all_accounts': all_accounts,
        'account_0': account_0,
        'account_1': account_1,
        'account_2': account_2,
        'acc_total': acc_total,

        'sum_total0': sum(total_bank0),
        'sum_total1': sum(total_bank1),
        'sum_total2': sum(total_bank2),
    }
    return render(request, 'platforms/total_accounts.html', context)

# 2. 상세 계좌 페이지


def accounts(request, pk):
    account = get_object_or_404(Account, pk=pk)
    all_trans = account.trans.all().order_by('-id')
    tmp_trans = account.trans.all()

    trans_sum = sum(all_trans.values_list('trans_price', flat=True))
    totals = []
    result = 0
    for trans in tmp_trans:
        result += trans.trans_price
        totals.append(result)
    totals = totals[::-1]
    datas = zip(all_trans, totals)
    context = {
        "account": account,
        "all_trans": datas,
        'trans_sum': trans_sum,
    }
    return render(request, 'platforms/accounts.html', context)

# 3. 이체 페이지


def transfer(request, pk):
    account = Account.objects.get(pk=pk)
    if request.method == 'POST':
        # 내 계좌번호
        acc_pwd = request.POST['acc_pwd']
        acc_pwd = int(acc_pwd)
        # 입력받은 계좌 비번이랑 현재 비번이랑 일치할 때 이체 시작
        if account.acc_pwd == acc_pwd:
            # 거래 시간 얻기
            trans_date = datetime.datetime.now()
            trans_date = trans_date.replace(microsecond=0)

            # 보낼 계좌번호
            acc_num = request.POST['acc_num']

            # 금액을 int로 변환
            price = request.POST['trans_price']
            price = int(price)

            # 문구
            youContent = request.POST['youContent']
            meContent = request.POST['meContent']

            myTrans = Trans(trans_date=trans_date, trans_price=-price,
                            trans_content=meContent, trans_type=3, account_id=account.acc_num)
            youtTrans = Trans(trans_date=trans_date, trans_price=price,
                              trans_content=youContent, trans_type=3, account_id=acc_num)

            myTrans.save()
            youtTrans.save()
            return redirect('platforms:total_accounts')
    else:
        context = {
            "account": account
        }
        return render(request, 'platforms/transfer.html', context)

# 4. 지점찾기 페이지


def find_kb(request):
    return render(request, 'platforms/find_kb.html')

# --------- 증권 (주식계좌, 주식잔고, 주식차트, 종가 UP&DOWN-출석체크,결과보기) ---------
# 5. 주식 계좌 페이지


def stock_account(request):
    all_accounts = Account.objects.filter(
        user=request.user)  # 해당 user에 해당하는 계좌 list
    stock_acc = all_accounts.filter(acc_type=1)  # user의 증권 계좌

    total_bank0 = []
    for i in range(len(stock_acc)):
        tmp = 0
        all_trans = Trans.objects.filter(account_id=stock_acc[i].acc_num)
        tmp_acc = Account.objects.get(acc_num=stock_acc[i].acc_num)
        for trans in all_trans:
            tmp += trans.trans_price
        total_bank0.append(tmp)
        tmp_acc.total = tmp
        tmp_acc.save()

    context = {
        'all_accounts': stock_acc
    }
    return render(request, 'platforms/stock_account.html', context)

# 6. 주식 잔고 페이지


def stock(request):
    return render(request, 'platforms/stock.html')

# 7. 주식 차트 페이지


def stock_charts(request):
    return render(request, 'platforms/stock_charts.html')

# 8. 종가 UP&DOWN 페이지


def stock_game(request):
    # 마지막 ID로 주기!
    model = LSTM.objects.get(id=130)
    pred = model.pred

    context = {
        'pred': pred,
    }
    return render(request, 'platforms/stock_game.html', context)

# 9. 출석체크 페이지


def attendance(request):
    goldbaby = request.user
    model = LSTM.objects.get(id=130)
    act = model.act

    if goldbaby.tmp == -1:
        if act == goldbaby.my_result:
            goldbaby.success += 1
            goldbaby.save()

            trans_date = datetime.datetime.now()
            trans_date = trans_date.replace(microsecond=0)
            myTrans = Trans(trans_date=trans_date, trans_price=0.0019,
                            trans_content="KB금쪽리워드환급", trans_type=3, account_id="110-378-912021")
            myTrans.save()

    return render(request, 'platforms/attendance.html')

# 10. 결과보기 페이지


def updown_result(request):
    model = LSTM.objects.get(id=130)
    act = model.act
    user_act = request.user.my_result

    context = {
        'act': act,
        'user_act': user_act,
    }
    return render(request, 'platforms/updown_result.html', context)

# ----------------------------- 카드 (카드목록, 카드추천) -----------------------------
# 11. 카드목록 페이지


def cards(request):
    check_cards = Card.objects.filter(card_type=0)  # 체크카드 목록
    debit_cards = Card.objects.filter(card_type=1)  # 신용카드 목록

    benefits = Benefit.objects.all()  # 카드 혜택 목록
    context = {
        'check_cards': check_cards,
        'debit_cards': debit_cards,
        'benefits': benefits,
    }
    return render(request, 'platforms/cards.html', context)

# 12. 카드추천 페이지


def cards_recom(request):
    ### ========= 카드추천 알고리즘 ========= ###
    cards = [0, 0, 0, 0, 0, 0, 0]

    all_accounts = Account.objects.filter(
        user=request.user)  # 해당 user에 해당하는 계좌 list
    all_accounts = all_accounts.filter(
        acc_type=0)   # 해당 user의 은행 계좌만 (증권, 금 제외)

    # for 알고리즘
    cards = [0, 0, 0, 0, 0, 0, 0, 0]
    for j in range(len(cards)):
        # card 0번째 5번째 object 없음
        if j == 0 or j == 5:
            continue
        # 그렇지 않으면 확인 !
        else:
            # 카드에 해당 하는 benefits 뽑아내기
            benefits = Benefit.objects.filter(card_id=j)
            for i in range(len(all_accounts)):
                all_trans = Trans.objects.filter(
                    account_id=all_accounts[i].acc_num)

                for trans in all_trans:
                    # if trans.trans_date.year==2022 and trans.trans_date.month==3:
                    if trans.trans_date.year == 2022:
                        # 출금일 때만 type 체크
                        if trans.trans_price < 0:
                            # benefit 확인
                            for benefit in benefits:
                                # 해당 내용이 컨텐츠 안에 있다면
                                if trans.trans_content.find(benefit.service_name) != -1:
                                    # 할인이 %인것만
                                    if benefit.percent < 100:
                                        cards[j] += (trans.trans_price * -
                                                     1) * benefit.percent

    # 1, 3, 4
    check_max = max(cards[1], cards[3], cards[4])

    # 2, 6, 7
    debit_max = max(cards[2], cards[6], cards[7])

    for i in range(len(cards)):
        if cards[i] == check_max:
            check_id = i
        elif cards[i] == debit_max:
            debet_id = i

    # for 차트
    types = [0, 0, 0, 0, 0, 0]
    # 은행 계좌 for문
    for i in range(len(all_accounts)):
        all_trans = Trans.objects.filter(account_id=all_accounts[i].acc_num)
        for trans in all_trans:
            if trans.trans_date.year == 2022 and trans.trans_date.month == 5:
                # 출금일 때만 type 체크
                if trans.trans_price < 0:
                    # 소비 type이 0인 경우 :: 식비
                    if trans.trans_type == 0:
                        types[0] += trans.trans_price
                    # 소비 type이 1인 경우 :: 이동통신
                    elif trans.trans_type == 1:
                        types[1] += trans.trans_price
                    # 소비 type이 2인 경우 :: 쇼핑
                    elif trans.trans_type == 2:
                        types[2] += trans.trans_price
                    # 소비 type이 3인 경우 :: 문화생활
                    elif trans.trans_type == 3:
                        types[3] += trans.trans_price

platforms/templates/platforms/index.html
{% extends 'base.html' %}

{% block content %}
<main id="main" class="main" style="margin-left:0; margin-right:0;">
  <p>
    {{user.user_name}}
  </p>
  <!-- START slide images -->
  <div id="demo" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ul class="carousel-indicators">
      <li data-target="#demo" data-slide-to="0" class="active"></li>
      <li data-target="#demo" data-slide-to="1"></li>
      <li data-target="#demo" data-slide-to="2"></li>
      <li data-target="#demo" data-slide-to="3"></li>
    </ul>
    
    <!-- The slideshow -->
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="../../../assets/img/kb_main1.jpg" alt="1" width="1100" height="500">
      </div>
      <div class="carousel-item">
        <img src="../../../assets/img/kb_main2.jpg" alt="2" width="1100" height="500">
      </div>
      <div class="carousel-item">
        <img src="../../../assets/img/kb_main3.jpg" alt="3" width="1100" height="500">
      </div>
      <div class="carousel-item">
        <img src="../../../assets/img/kb_main4.jpg" alt="4" width="1100" height="500">
      </div>
    </div>
    
    <!-- Left and right controls -->
    <a class="carousel-control-prev" href="#demo" data-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </a>
    <a class="carousel-control-next" href="#demo" data-slide="next">
      <span class="carousel-control-next-icon"></span>
    </a>
  </div>
  <!-- END slide images -->

  <div id="kb_oneline" class="container-fluid">
    <div class="row"  style="text-align:center;">
      <p style="font-size:17px; color:gray;">한번에, 한곳에서, 편리하게!</p>
      <p style="font-size:23px; font-weight:bold;">KB국민은행은 금융 통합 플랫폼으로의 확장을 선도합니다.</p>
    </div>
  </div>

  <div id="kb_content" class="container-fluid">
    <div class="row">
      <div class="offset-lg-2 col-lg-2" style="text-align:center;">
        <img src="../../../assets/img/pattern.png">
        <h3 style="font-size:18px; font-weight:bold; margin-bottom:20px;">나만을 위한 소비습관</h3>
        <p style="font-size:14px; color:gray;">월별, 요일별, 업종별 <br>지출내역 분석으로<br>나의 소비 현황을 알려드립니다.</p>
        <a href="{% url 'platforms:charts' %}" style="font-size:17px; text-decoration:underline; !important;">소비습관 진단하러 가기</a>
      </div>
  
      <div class="offset-lg-1 col-lg-2" style="text-align:center;">
        <img src="../../../assets/img/game.png">
        <h3 style="font-size:18px; font-weight:bold; margin-bottom:20px;">주식 종가 UP&DOWN 맞추기</h3>
        <p style="font-size:14px; color:gray;">일상 속 즐거운 금융습관을<br>만들기 위해 <br> 종가 등락 예측 서비스를 제공합니다.</p>
        <a href="{% url 'platforms:stock_game' %}" style="font-size:17px; text-decoration:underline; !important;">"UP&DOWN" 서비스 바로가기</a>
      </div>
  
      <div class="offset-lg-1 col-lg-2" style="text-align:center;">
        <img src="../../../assets/img/gold.png">
        <h3 style="font-size:18px; font-weight:bold; margin-bottom:20px;">KB 금쪽 Life</h3>
        <p style="font-size:14px; color:gray;">KB는 변하지 않는 가치와 함께합니다.<br>"UP&DOWN" 예측 성공하고<br>금 받아가세요.</p>
        <a href="{% url 'platforms:myGold' %}" style="font-size:17px; text-decoration:underline; !important;">내 gold 현황 확인하기</a>
      </div>
    </div>
  </div>
  
  <!-- APP 사진 정렬 -->
  {% comment %} <div id="kb_app" class="container">
    <div class="row">
      <h2 style="font-size:23px; font-weight:bold; margin-bottom:20px">KB APP.</h2>
      <img src="../assets/img/kb_국민은행.png" style="width:90px; height:70px;"><br>
      <p>KB 스타뱅킹</p>
    </div>
  </div> {% endcomment %}
</main><!-- End #main -->

{% endblock content %}

platforms/templates/platforms/stock_account.html
{% extends 'base.html' %}

{% block content %}
<style>
  button {
    background: none;
    /* border: 3px solid #1f2023; */
    border-radius: 5px;
    color: #1f2023;
    display: block;
    /* font-size: 1.6em; */
    /* font-weight: bold; */
    /* margin: 1em auto; */
    /* padding: 2em 6em; */
    position: relative;
    text-transform: uppercase;
  }
  
  button::before,
  button::after {
    background: #1f2023;
    content: '';
    position: absolute;
    z-index: -1;
  }
  
  button:hover {
    color: #d3d2d2;
  }
  .btn-2::after {
    height: 100%;
    left: 0;
    top: 0;
    width: 0;
  }
  .btn-2{
    border-color: #545045;
    background-color: #545045;
    color: #ffffff;
  }
  .btn-2:hover:after {
    width: 100%;
    color: #ffffff;
  }

    th{
        font-size: 18px;
    }
    td{
        font-size: 15px;
    }
    p{
        font-size: 15px;
    }
    tr{
        font-size : 15px;
    }

  </style>

<main id="main" class="main">

    <div class="pagetitle">
      <h1>나의 계좌 조회</h1>
    </div><!-- End Page Title -->

    <section class="section">
      <div class="row">
        <div class="col-lg-12">

          <div class="card">
            <div class="card-body">
              <hr style="color: #545045; height : 4px;">
              <h5 class="card-title"><b>증권계좌</b></h5>
              <hr style="color: #545045; height : 4px;">

              <!-- Table with stripped rows -->
              <table class="table">
                <thead>
                  <tr>
                    <th scope="col">계좌명</th>
                    <th scope="col">계좌번호</th>
                    <th scope="col">신규일</th>
                    <th scope="col">최근거래일</th>
                    <th scope="col">잔액(원)</th>
                    <th scope="col" style="text-align: center;">업무　　　</th>
                  </tr>
                </thead>
                <tbody>
                  {% if user.is_authenticated %}
                    {% for account in all_accounts %}
                      <tr  onmouseover="this.style.backgroundColor='#ffe168'" onmouseout="this.style.backgroundColor=''">
                        <td>{{account.acc_name}}</td>
                        <td>{{account.acc_num}}</td>
                        <td>{{account.created_at|date:"Y-m-d"}}</td>
                        <td>{{account.updated_at|date:"Y-m-d"}}</td>
                        <td>{{account.total|floatformat:"0"}}</td>
                        <td>
                          <div style="display: inline;">
                            <a href="{% url 'platforms:accounts' account.pk %}">
                              <button class="btn-2" style=" display: inline; ">
                                조회
                              </button>
                            <a href="{% url 'platforms:transfer' account.pk %}">
                            <button class="btn-2" style=" display: inline;">
                              이체
                            </button>
                          </div>
                        </td>
                      </tr>
                    
                </tbody>
              </table>
              <div style="float:left"><h5><b>증권계좌 총잔액</b></h5></div>
              <div style="float: right; margin-right: 100px;"><h5><b>{{account.total|floatformat:"0"}}원</b></h5></div> 
              {% endfor %}
              {% endif %}
              <br>
              <br>
              <br>
              <!-- End Table with stripped rows -->
              
            </div>
          </div>
        </div>
      </div>
    </section>

</main><!-- End #main -->

  
{% endblock content %}

platforms/templates/platforms/updown_result.html
<div class="user-wrap">
    <div class="user-image">
        <!-- 실제 결과 값이 하락일 때 -->
        {% if act == 0 %}
            <!-- 나의 예측 값이 하락일 때 -->
            {% if user_act == 0 %}
            <img src="../../../assets/img/updown_result_하하.png" width="900">
            <!-- 나의 예측 값이 상승 일 때 -->
            {% else %}
            <img src="../../../assets/img/updown_result_상하.png" width="900">
            {% endif %}
        <!-- 실제 결과 값이 상승일 때 -->
        {% else %}
            <!-- 나의 예측 값이 하락일 때 -->
            {% if user_act == 0 %}
            <img src="../../../assets/img/updown_result_하상.png" width="900">
            <!-- 나의 예측 값이 상승일 때 -->
            {% else %}
            <img src="../../../assets/img/updown_result_상상.png" width="900">
            {% endif %}
        {% endif %}
    </div>
</div>