accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('register/', views.register, name="register"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('platforms/', include('platforms.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

platforms/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'platforms'
urlpatterns = [
    # main 화면
    path('index/', views.index, name="index"),
    
    # 은행 (전체계좌-상세계좌, 이체, 지점찾기)
    path('total_accounts/', views.total_accounts, name="total_accounts"),   # 전체계좌
    path('<str:pk>/accounts/', views.accounts, name="accounts"),                     # 상세계좌
    path('<str:pk>/transfer/', views.transfer, name="transfer"),            # 이체
    path('find_kb/', views.find_kb, name="find_kb"),                        # 지점찾기

    # 증권 (주식계좌, 주식잔고, 주식차트, 종가 UP&DOWN-출석체크,결과보기)
    path('stock_account/', views.stock_account, name="stock_account"),      # 주식 전체계좌
    path('stock/', views.stock, name="stock"),                              # 주식 잔고
    path('stock_charts/', views.stock_charts, name="stock_charts"),         # 주식 차트
    path('stock_game/', views.stock_game, name="stock_game"),               # 종가UP&DOWN
    path('attendance/', views.attendance, name="attendance"),               # 출석체크
    path('updown_result/', views.updown_result, name="updown_result"),      # 결과

    # 카드 (카드목록, 카드추천)
    path('cards/', views.cards, name="cards"),                              # 카드목록
    path('cards_recom/', views.cards_recom, name="cards_recom"),            # 카드추천

    # 습관 (소비습관, 자산현황, myGold 확인하기)
    path('charts/', views.charts, name="charts"),                           # 소비습관
    path('myAsset/', views.myAsset, name="myAsset"),                        # 자산현황
    path('myGold/', views.myGold, name="myGold"),                           # my Gold
    path('setResult/', views.setResult, name="setResult")                   # 예측 값 받아서 정리

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>KB Platform</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/../assets/img/kb.png" rel="icon">
  <link href="/../assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/../assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/../assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/../assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="/../assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="/../assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="/../assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="/../assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

  <!-- Template Main CSS File -->
  <link href="/../assets/css/style.css" rel="stylesheet">
  <!-- =======================================================
  * Template Name: NiceAdmin - v2.2.2
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a href="{% url 'platforms:index' %}" class="logo d-flex align-items-center">
        <img src="/../assets/img/kb.png" alt="kb_logo">
        <span class="d-none d-lg-block" style='margin-left:5px; color:#2c2c2b; font-size:'>KB platform</span>
      </a>
    </div><!-- End Logo -->

    <nav class="navbar navbar-expand-sm">
      <!-- Links -->
      <ul class="navbar-nav">
        <!-- Dropdown -->
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="navbardrop" data-toggle="dropdown">
            은행
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'platforms:total_accounts' %}">계좌 조회 및 이체</a>
            <a class="dropdown-item" href="{% url 'platforms:find_kb' %}">지점 찾기</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="navbardrop" data-toggle="dropdown">
            증권
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'platforms:stock_account' %}">계좌 조회 및 이체</a>
            <a class="dropdown-item" href="{% url 'platforms:stock' %}">내 주식 잔고</a>
            <a class="dropdown-item" href="{% url 'platforms:stock_charts' %}">주식 차트</a>
            <a class="dropdown-item" href="{% url 'platforms:stock_game' %}">종가 예측 UP & DOWN</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="navbardrop" data-toggle="dropdown">
            카드
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'platforms:cards' %}">카드 목록</a>
            <a class="dropdown-item" href="{% url 'platforms:cards_recom' %}">카드 추천</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" id="navbardrop" data-toggle="dropdown">
            MY 습관
          </a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{% url 'platforms:charts' %}">나의 소비습관</a>
            <a class="dropdown-item" href="{% url 'platforms:myAsset' %}">나의 자산현황</a>
            <a class="dropdown-item" href="{% url 'platforms:myGold' %}">나의 Gold 확인하기</a>
          </div>
        </li>
      </ul>
    </nav>


    <nav class="header-nav ms-auto" style="font-size:1rem;">
      {% if user.is_authenticated %}
      <span>
        <span style="margin-right:15px">{{user.first_name}}님, 환영합니다.</span>
        <a href="{% url 'accounts:logout' %}"><span style="margin-right:15px">로그아웃</span></a>
      </span>
      {% else %}
        <a href="{% url 'accounts:login' %}"><span style="margin-right:15px">로그인</span></a>
        <a href="{% url 'accounts:register' %}"><span style="margin-right:15px">회원가입</span></a>
      {% endif %}
    </nav><!-- End Icons Navigation -->
  </header><!-- End Header -->

  {% block content %}
  {% endblock content %}

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer" style="border-top: 1px solid #eaeaea;">
    <div class="copyright">
      &copy; Copyright <strong><span>K-금쪽이</span></strong>. All Rights Reserved
    </div>
    
  </footer><!-- End Footer -->
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="/../assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="/../assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/../assets/vendor/chart.js/chart.min.js"></script>
  <script src="/../assets/vendor/echarts/echarts.min.js"></script>
  <script src="/../assets/vendor/quill/quill.min.js"></script>
  <script src="/../assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="/../assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="/../assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/../assets/js/main.js"></script>
</body>

</html>